name: upload-snapshot

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Execution permission for Gradle wrapper
        run: chmod +x gradlew
      - name: Tests
        run: ./gradlew check
        env:
          TEST_PROFILE: ci
      - name: Upload snapshot to Maven Central
        run: ./gradlew build uploadSnapshot
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ossrhUsername }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ossrhPassword }}
